### ISSUE TITLE
Script freezes without producing output

### ISSUE THREAD

**Issue by csaftoiu** [bernd/wunderlist-backup#1]
The script appears to get stuck. After a few minutes I CTRL+C it and get this output:

```
MacBook-Pro-4:Wunderlist csaftoiu$ ruby wunderlist-backup.rb
^C/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:155:in `select': Interrupt
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:155:in `rescue in rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:152:in `rbuf_fill'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:134:in `readuntil'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/protocol.rb:144:in `readline'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:39:in `read_status_line'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http/response.rb:28:in `read_new'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1412:in `block in transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1409:in `transport_request'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:1382:in `request'
	from wunderlist-backup.rb:85:in `block in get'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:852:in `start'
	from wunderlist-backup.rb:85:in `get'
	from wunderlist-backup.rb:65:in `block (2 levels) in <class:WunderHTTP>'
	from wunderlist-backup.rb:149:in `block in <main>'
	from wunderlist-backup.rb:145:in `each'
	from wunderlist-backup.rb:145:in `<main>'

```

Any ideas what the issue might be?

**Comment by csaftoiu** [comment]
Never mind - I have 80 lists, it's just taking a while to go through them all :).
